location              = "UK South"
resource_group_name   = "rg-container-demo"
acr_name              = "acrcontainerdemo"
app_service_plan_name = "service-plan-container-demo"
web_app_name          = "WebAppContainerDemo2025"
docker_image_name     = "containerDemoApp:latest"
